version: '3'

services:
  # MySQL数据库
  mysql:
    image: mysql:8
    container_name: chess_mysql_prod
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 8prvp55k
      MYSQL_DATABASE: chinese_chess_db
    volumes:
      - mysql_data:/var/lib/mysql
      - ./server/config/database.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - chess_network
    command: --default-authentication-plugin=mysql_native_password

  # 后端API服务
  server:
    image: chinese-chess-server:latest
    container_name: chess_server_prod
    restart: always
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=chinese_chess_db
      - DB_USER=root
      - DB_PASSWORD=8prvp55k
      - PORT=5000
      - NODE_ENV=production
      - CLIENT_URL=https://chess.example.com
    ports:
      - "5000:5000"
    networks:
      - chess_network

  # 前端服务
  client:
    image: chinese-chess-client:latest
    container_name: chess_client_prod
    restart: always
    depends_on:
      - server
    ports:
      - "80:80"
      - "443:443"
    networks:
      - chess_network
    volumes:
      - ./ssl:/etc/nginx/ssl

networks:
  chess_network:
    driver: bridge

volumes:
  mysql_data: 